name: Build dashboard data (artifact only)

on:
  workflow_dispatch: {}
  push:
    branches: [ main, chore/ci-enable-pages ]
    paths:
      - "scripts/**"
      - "package*.json"
      - ".github/workflows/deploy-pages.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate dashboard data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PROJECT_NUMBER: 1
        run: |
          npx tsx scripts/generate-dashboard-data.ts
          ls -l docs || true
          head -n 50 docs/dashboard-data.json || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-data
          path: docs/dashboard-data.json
          if-no-files-found: error
