name: route-event

on:
  push:
    branches: [ main ]
  pull_request:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]
  issue_comment:
    types: [created, edited]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

jobs:
  route-event:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm

      - name: Install dependencies (if lockfile exists)
        run: |
          set -e
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm i --frozen-lockfile
          elif [ -f yarn.lock ]; then
            corepack enable
            yarn install --frozen-lockfile
          else
            echo "no lockfile; skip install"
          fi

      - name: Route Issue Event
        if: ${{ github.event_name == 'issues' }}
        run: |
          if [ -f scripts/webhook-router.ts ]; then
            npx -y tsx scripts/webhook-router.ts issues
          else
            echo "skip: scripts/webhook-router.ts not found"
          fi

      - name: Route PR Event
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [ -f scripts/webhook-router.ts ]; then
            npx -y tsx scripts/webhook-router.ts pull_request
          else
            echo "skip: scripts/webhook-router.ts not found"
          fi

      - name: Route Push Event
        if: ${{ github.event_name == 'push' }}
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          echo "🔹 Push Event: $BRANCH_NAME @ $COMMIT_SHA"
          if [ -f scripts/webhook-router.ts ]; then
            npx -y tsx scripts/webhook-router.ts push
          else
            echo "skip: scripts/webhook-router.ts not found"
          fi

      - name: Route Comment Event
        if: ${{ github.event_name == 'issue_comment' }}
        run: |
          if [ -f scripts/webhook-router.ts ]; then
            npx -y tsx scripts/webhook-router.ts issue_comment
          else
            echo "skip: scripts/webhook-router.ts not found"
          fi
