name: route-event

on:
  push:
    branches: [ main ]
  pull_request:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

jobs:
  route-event:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm

      - name: Install dependencies (if lockfile exists)
        run: |
          set -e
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "no lockfile; using npx tsx"
          fi

      # Issues
      - name: Route Issue Event
        if: ${{ github.event_name == 'issues' }}
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_ACTION: ${{ github.event.action }}
          ISSUE_TITLE:  ${{ github.event.issue.title }}
          ISSUE_LABELS: ${{ toJson(github.event.issue.labels) }}
        run: |
          export ISSUE_TITLE ISSUE_LABELS
          npx -y tsx scripts/cicd/webhook-router.ts issue "$ISSUE_ACTION" "$ISSUE_NUMBER"

      # Pull Request
      - name: Route PR Event
        if: ${{ github.event_name == 'pull_request' }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_ACTION: ${{ github.event.action }}
          PR_TITLE:  ${{ github.event.pull_request.title }}
        run: |
          export PR_TITLE
          npx -y tsx scripts/cicd/webhook-router.ts pr "$PR_ACTION" "$PR_NUMBER"

      # Push
      - name: Route Push Event
        if: ${{ github.event_name == 'push' }}
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_SHA:  ${{ github.sha }}
        run: |
          echo "🔹 Push Event: $BRANCH_NAME @ $COMMIT_SHA"
          # CLI仕様: <event> <action> <branch> <sha> （actionは未使用なので"_"）
          npx -y tsx scripts/cicd/webhook-router.ts push "_" "$BRANCH_NAME" "$COMMIT_SHA"

      # Issue Comment
      - name: Route Comment Event
        if: ${{ github.event_name == 'issue_comment' }}
        env:
          ISSUE_NUMBER:   ${{ github.event.issue.number }}
          COMMENT_BODY:   ${{ github.event.comment.body }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
          COMMENT_ACTION: ${{ github.event.action }}
        run: |
          export COMMENT_BODY COMMENT_AUTHOR
          npx -y tsx scripts/cicd/webhook-router.ts comment "$COMMENT_ACTION" "$ISSUE_NUMBER"
